baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Arian | ART'
theme = 're-terminal'
pagination.pagerSize = 5

[languages]
  [languages.en.params]
    languageName = "English"
    title = "Arian | ART"
    subtitle = "Programming + Art"
    owner = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    minuteReadingTime = "min read"
    words = "words"

    [languages.en.params.logo]
      logoText = "Arian | ART"
      logoHomeLink = "/"

    [languages.en.menu]
      # Submenus is available since v2.1.0
      # [[languages.en.menu.main]]
      #   identifier = "submenuParent"
      #   name = "Submenu"
      # [[languages.en.menu.main]]
      #   parent = "submenuParent"
      #   identifier = "anItem"
      #   name = "AnItem"
      # [[languages.en.menu.main]]
      #   identifier = "about"
      #   name = "About"
      #   url = "/about"
      # [[languages.en.menu.main]]
      #   identifier = "showcase"
      #   name = "Showcase"
      #   url = "/showcase"
